name: leap_standard_platformer
description: Platformer example to showcase the usage of Leap with Flame
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.5.0
  flame_audio: ^1.3.3
  flame_tiled: ^1.9.0
  flutter:
    sdk: flutter
  leap:
    path: ../../packages/leap

dev_dependencies:
  flame_lint: ^0.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/audio/die.wav
    - assets/audio/coin.wav
    - assets/audio/jump.wav
    - assets/audio/spawn.wav
    - assets/audio/village_music.mp3
    - assets/images/level_ice_tileset.png
    - assets/images/level_standard_tileset.png
    - assets/images/repeatable_background.png
    - assets/images/player_spritesheet.png
    - assets/tiles/map.tmx
