name: leap_standard_platformer
description: Platformer example to showcase the usage of Leap with Flame
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.2

dependencies:
  flame: ^1.10.0
  flame_audio: ^2.1.1
  flame_tiled: ^1.15.0
  flutter:
    sdk: flutter
  leap:
    path: ../../packages/leap
  tiled: ^0.10.1

dev_dependencies:
  flame_lint: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/die.wav
    - assets/audio/coin.wav
    - assets/audio/jump.wav
    - assets/audio/spawn.wav
    - assets/audio/village_music.mp3
    - assets/images/level_ice_tileset.png
    - assets/images/level_standard_tileset.png
    - assets/images/repeatable_background.png
    - assets/images/player_spritesheet.png
    - assets/tiles/map.tmx
