name: cicd

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]


env:
  FLUTTER_MIN_VERSION: '3.13.0'

jobs:
  # BEGIN LINTING STAGE
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2
      - run: melos run format-check

  analyze-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2
      - name: "Analyze with latest stable"
        uses: invertase/github-action-dart-analyzer@v2.0.0
        with:
          fatal-infos: true
  # END LINTING STAGE

  # BEGIN TESTING STAGE
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - uses: bluefireteam/melos-action@v2
      - name: Run tests
        run: melos test
  # END TESTING STAGE